#############################################################################
#  CONSUL
#############################################################################
consul:
  image: progrium/consul:latest
  labels:
    - triton.cns.services=consul
  restart: always
  mem_limit: 128m
  expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
  env_file: .env
  ports:
    - 8500:8500
  command: -server -bootstrap -ui-dir /ui
#############################################################################
#  MONGO
#############################################################################
mongo:
  build: ./mongo
  labels:
    - triton.cns.services=mongo
  env_file: .env
  ports:
    - 27017:27017
#############################################################################
#  ROCKET.CHAT
#############################################################################
rocketchat:
  build: ./rocketchat
  labels:
    - triton.cns.services=rocketchat
  env_file: .env
  environment:
    - PORT=3000
  ports:
    - 3000:3000
